name: Atlas Frontend (Next.js)
on:
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  scaffold_frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create Next.js frontend structure
        run: |
          mkdir -p frontend/pages frontend/components frontend/lib
          cat > frontend/package.json <<'JSON'
          {
            "name": "atlas-frontend",
            "private": true,
            "scripts": {
              "dev": "next dev",
              "build": "next build",
              "start": "next start"
            },
            "dependencies": {
              "next": "14.2.5",
              "react": "18.2.0",
              "react-dom": "18.2.0"
            }
          }
          JSON

          cat > frontend/next.config.js <<'JS'
          /** @type {import('next').NextConfig} */
          const nextConfig = { reactStrictMode: true };
          module.exports = nextConfig;
          JS

          cat > frontend/pages/index.tsx <<'TSX'
          import { useEffect, useState } from "react";

          export default function Home() {
            const [status, setStatus] = useState<string>("...");
            useEffect(() => {
              fetch((process.env.NEXT_PUBLIC_API_BASE_URL || "http://localhost:8000") + "/health")
                .then(r => r.json())
                .then(d => setStatus(d.ok ? "OK" : "Fail"))
                .catch(() => setStatus("Error"));
            }, []);
            return (
              <main style={{ padding: 20, fontFamily: "sans-serif" }}>
                <h1>Atlas Dashboard</h1>
                <p>API health: <b>{status}</b></p>
              </main>
            );
          }
          TSX

      - name: Commit frontend scaffold
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "feat(frontend): scaffold minimal Next.js frontend"
